'use client';

import Image from 'next/image';
import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { AnimatePresence, MotionConfig, motion, useReducedMotion } from 'motion/react';
import { ArrowDown, ArrowRight, ArrowUpRight, BadgeCheck, BriefcaseBusiness, CalendarDays, CarFront, Check, ChevronDown, Clock3, Heart, Luggage, MapPin, Menu, MessageCircle, Mountain, Phone, Plane, Quote, Route, ShieldCheck, Sparkles, Users, Wallet, X, type LucideIcon } from 'lucide-react';
import { business, createWhatsAppUrl, enquiry } from '@/config/business';
import { destinations, faqs, fleet, services } from '@/data/content';
import { testimonials, testimonialPlaceholders } from '@/data/testimonials';

const nav = [['Home', '#home'], ['Services', '#services'], ['Fleet', '#fleet'], ['Why Us', '#why-us'], ['Reviews', '#reviews'], ['FAQ', '#faq']];
const icons: Record<string, LucideIcon> = { car: CarFront, plane: Plane, route: Route, mountain: Mountain, briefcase: BriefcaseBusiness, heart: Heart };

function Reveal({ children, className = '', delay = 0 }: { children: ReactNode; className?: string; delay?: number }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={{ opacity: 0, y: reduced ? 0 : 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.08 }} transition={{ duration: reduced ? 0 : 0.55, delay }}>{children}</motion.div>;
}
function WhatsApp({ children = 'Book on WhatsApp', message = enquiry(), className = '' }: { children?: ReactNode; message?: string; className?: string }) {
  return <motion.a whileHover={{ scale: 1.025 }} whileTap={{ scale: 0.98 }} href={createWhatsAppUrl(message)} target="_blank" rel="noopener noreferrer" className={`button whatsapp ${className}`}><MessageCircle size={19} />{children}<ArrowUpRight size={17} /></motion.a>;
}
function Call({ className = '' }: { className?: string }) { return <a className={`button call ${className}`} href={`tel:${business.phone}`}><Phone size={17} />Call Now</a>; }
function Heading({ eyebrow, title, text, centered = false }: { eyebrow: string; title: string; text?: string; centered?: boolean }) { return <div className={`section-heading ${centered ? 'centered' : ''}`}><span className="eyebrow"><span />{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div>; }

function Header() {
  const [open, setOpen] = useState(false);
  useEffect(() => { const close = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);
  return <header className="header"><div className="container header-inner"><a href="#home" className="brand" aria-label="Ganpati Travel Solutions home"><Image src="/images/logo.png" alt="Ganpati Travel Solutions" width={408} height={306} priority /></a><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([name, href]) => <a key={href} href={href}>{name}</a>)}</nav><div className="header-actions"><Call /><button className="menu-toggle" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} aria-controls="mobile-nav" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></div><AnimatePresence>{open && <motion.nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation" initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}>{nav.map(([name, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{name}<ArrowUpRight size={16} /></a>)}</motion.nav>}</AnimatePresence></header>;
}
function Hero() {
  const reduced = useReducedMotion();
  const item = { hidden: { opacity: 0, y: reduced ? 0 : 20 }, show: { opacity: 1, y: 0, transition: { duration: reduced ? 0 : 0.6 } } };
  return <section className="hero" id="home"><div className="container hero-grid"><motion.div className="hero-copy" variants={{ show: { transition: { staggerChildren: 0.11 } } }} initial="hidden" animate="show"><motion.div variants={item} className="location-pill"><span className="live-dot" /><MapPin size={14} /> YOUR JOURNEY STARTS IN RANCHI</motion.div><motion.p variants={item} className="hero-kicker">Local Rides <span>•</span> Airport Transfers <span>•</span> Outstation Trips</motion.p><motion.h1 variants={item}>Your Ride,<br /><span>Your Way.</span><svg className="headline-swoosh" viewBox="0 0 310 16" aria-hidden="true"><path d="M3 10 Q155 -3 304 8 M24 15 Q171 4 285 13" fill="none" stroke="#0878f9" strokeWidth="3" strokeLinecap="round" /></svg></motion.h1><motion.h2 variants={item}>Comfortable, Reliable &amp; On-Time<br className="desktop-break" /> Taxi Booking for Every Journey.</motion.h2><motion.p variants={item} className="hero-description">From everyday rides to unforgettable getaways. Book local, airport, outstation and family travel directly with Ganpati Travel Solutions.</motion.p><motion.div variants={item} className="cta-row"><WhatsApp /><Call className="outline" /></motion.div><motion.div variants={item} className="hero-reassurance"><ShieldCheck size={16} /><span>Your trip. Your choice. Direct booking assistance.</span></motion.div></motion.div><motion.div className="hero-visual" initial={{ opacity: 0, x: reduced ? 0 : 35 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.8, delay: 0.2 }}><div className="hero-photo"><Image src="/images/hero-taxi.webp" alt="Illustrative white travel taxi on a scenic green hill road" fill priority sizes="(max-width: 767px) 100vw, 52vw" /><div className="photo-shade" /><span className="image-label"><MapPin size={14} /> A little further. A little freer.</span></div><div className="ride-badge"><span className="round-icon"><CarFront size={23} /></span><div><strong>A ride for every plan</strong><span>City streets to scenic escapes</span></div><BadgeCheck className="blue" size={22} /></div><div className="journey-label"><Route size={17} /><span>Good journeys begin here.</span></div><span className="hero-caption">Illustrative travel visual</span></motion.div></div><div className="container trust-strip">{[[Route, 'Local & Outstation Travel'], [Plane, 'Airport Transfers'], [CarFront, 'Multiple Vehicle Options'], [MessageCircle, 'Direct Booking Assistance']].map(([Icon, label]) => { const I = Icon as LucideIcon; return <div key={String(label)}><I size={20} /><span>{String(label)}</span></div>; })}</div></section>;
}
function QuickBooking() {
  const [today, setToday] = useState('');
  const [ready, setReady] = useState('');
  useEffect(() => { const d = new Date(); setToday(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`); }, []);
  function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = e.currentTarget;
    const data = new FormData(form);
    for (const name of ['name', 'pickup', 'drop']) { const input = form.elements.namedItem(name) as HTMLInputElement; input.setCustomValidity(input.value.trim() ? '' : 'Please enter this detail.'); if (!input.reportValidity()) return; }
    const mobile = String(data.get('mobile')).replace(/[\s()-]/g, '');
    const mobileInput = form.elements.namedItem('mobile') as HTMLInputElement;
    mobileInput.setCustomValidity(/^(?:\+91|91)?[6-9]\d{9}$/.test(mobile) ? '' : 'Enter a valid Indian mobile number (10 digits, optionally +91).'); if (!mobileInput.reportValidity()) return;
    const date = String(data.get('date')); const dateInput = form.elements.namedItem('date') as HTMLInputElement;
    const d = new Date(); const currentDay = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
    dateInput.setCustomValidity(date < currentDay ? 'Please choose today or a future date.' : ''); if (!dateInput.reportValidity()) return;
    const message = `Hello ${business.name},\n\nI would like to enquire about a taxi booking.\n\nName: ${String(data.get('name')).trim()}\nMobile: ${mobile}\nPickup: ${String(data.get('pickup')).trim()}\nDrop: ${String(data.get('drop')).trim()}\nTravel Date: ${date}\nTrip Type: ${data.get('trip')}\nVehicle Preference: ${data.get('vehicle')}\n\nPlease share availability and fare details.`;
    const url = createWhatsAppUrl(message); setReady(url); window.open(url, '_blank', 'noopener,noreferrer');
  }
  return <section className="container booking-wrap" id="booking"><Reveal className="booking-card"><div className="booking-title"><div className="booking-title-left"><span className="round-icon"><Route size={24} /></span><div><h2>Where would you like to go?</h2><p>Get your taxi fare on WhatsApp. Let’s plan your ride.</p></div></div><span className="booking-note"><MessageCircle size={15} /> Direct enquiry. No complicated booking.</span></div><form onSubmit={submit} onInput={e => { const field = e.target as HTMLInputElement; if ('setCustomValidity' in field) field.setCustomValidity(''); setReady(''); }}><div className="form-grid"><label>Your name<input name="name" autoComplete="name" placeholder="Full name" required maxLength={80} /></label><label>Mobile number<input name="mobile" type="tel" inputMode="tel" autoComplete="tel" placeholder="Your mobile number" required maxLength={18} /></label><label>Pickup location<div className="input-icon"><MapPin size={16} /><input name="pickup" placeholder="Where from?" required maxLength={200} /></div></label><label>Drop location<div className="input-icon"><MapPin size={16} /><input name="drop" placeholder="Where to?" required maxLength={200} /></div></label><label>Travel date<input name="date" type="date" min={today} required aria-label="Travel date" /></label><label>Trip type<select name="trip" defaultValue="Local Taxi">{['Local Taxi', 'Airport Transfer', 'Outstation', 'Sightseeing', 'Family Trip', 'Corporate Travel', 'Wedding / Event Travel'].map(t => <option key={t}>{t}</option>)}</select></label><label>Vehicle preference<select name="vehicle" defaultValue="No Preference">{['Sedan', 'SUV', 'Innova / Crysta', '7 Seater', 'Group Travel Vehicle', 'No Preference'].map(t => <option key={t}>{t}</option>)}</select></label><button type="submit" className="button whatsapp form-submit"><MessageCircle size={18} />Get Fare on WhatsApp<ArrowUpRight size={17} /></button></div><div className="form-bottom"><span><ShieldCheck size={14} />Your details go directly to the team on WhatsApp.</span><span>Availability &amp; fare confirmed by the team.</span></div>{ready && <p className="form-status" role="status">Your enquiry is ready. Send it in WhatsApp to reach the team. <a href={ready} target="_blank" rel="noopener noreferrer">Open WhatsApp again <ArrowUpRight size={13} /></a></p>}</form></Reveal></section>;
}
function ProblemSection() {
  const problems = [[Clock3, 'Late or uncertain pickup', 'A delayed taxi can affect flights, meetings and travel plans.'], [Wallet, 'Unclear fare', 'Nobody wants to book a ride without knowing what to expect.'], [Luggage, 'The wrong vehicle', 'Too little luggage space or cramped seats can make a long journey feel longer.'], [Phone, 'Last-minute booking stress', 'Calling multiple drivers for an available taxi takes time you could spend planning.']] as const;
  return <section className="section problem-section"><div className="container"><Reveal><Heading eyebrow="LESS WORRY. MORE JOURNEY." title="Finding a reliable taxi shouldn’t be difficult." text="A flight to catch. Family to take along. Places to be. The last thing you need is uncertainty around your ride." centered /></Reveal><div className="problem-grid">{problems.map(([Icon, title, copy], i) => <Reveal key={title} delay={i * 0.06}><span className="problem-icon"><Icon size={24} /></span><h3>{title}</h3><p>{copy}</p></Reveal>)}</div></div></section>;
}
function CostSection() {
  return <section className="cost-section"><div className="container cost-grid"><Reveal><span className="eyebrow light"><span />YOUR TIME MATTERS</span><h2>One travel problem.<br />A whole journey affected.</h2><p>Your journey should start with confidence—<br />not uncertainty.</p></Reveal><div className="cost-points">{[[Plane, 'Rushing for a flight'], [BriefcaseBusiness, 'Delayed appointments'], [Users, 'Uncomfortable family journeys'], [Clock3, 'Last-minute taxi searches'], [CarFront, 'Uncertain vehicle availability'], [Route, 'Unnecessary travel stress']].map(([Icon, label], i) => { const I = Icon as LucideIcon; return <Reveal key={String(label)} delay={i * 0.04}><I size={22} /><span>{String(label)}</span></Reveal>; })}</div></div></section>;
}
function SolutionSection() {
  return <section className="section"><div className="container split-section"><Reveal className="solution-visual"><Image src="/images/airport-taxi.webp" alt="Illustrative sedan and travel luggage at an airport terminal" fill sizes="(max-width: 767px) 100vw, 45vw" /><div className="solution-caption"><MessageCircle size={22} /><div><strong>One conversation. A simpler journey.</strong><span>Speak directly with the people arranging your ride.</span></div></div></Reveal><Reveal className="solution-copy"><Heading eyebrow="MEET YOUR TRAVEL PARTNER" title="A simpler way to book your ride." /><p>Ganpati Travel Solutions helps you arrange local taxis, airport transfers, outstation journeys and sightseeing travel without a complicated booking process.</p><p>Just share your journey on WhatsApp or call us. We’ll help you check the vehicle options and fare.</p><div className="solution-checks">{['Simple WhatsApp booking', 'Local & outstation travel', 'Multiple vehicle options', 'Direct booking assistance'].map(x => <span key={x}><Check size={16} />{x}</span>)}</div><WhatsApp message={enquiry('a taxi for my upcoming journey')}>Check Availability</WhatsApp></Reveal></div></section>;
}
function ServicesSection() {
  return <section className="section pale-section" id="services"><div className="container"><Reveal className="heading-row"><Heading eyebrow="ONE TEAM. MANY WAYS TO GO." title="Every journey has a reason.
We have a ride for yours." /><p>From a quick ride across Ranchi to a well-deserved escape, choose the journey that fits your plans.</p></Reveal><div className="services-grid">{services.map((s, i) => { const Icon = icons[s.icon]; return <Reveal key={s.title} delay={(i % 3) * 0.07}><motion.article whileHover={{ y: -5 }} className="service-card"><div className="service-image"><Image src={`/images/${s.image}.webp`} alt={`${s.title} travel illustration`} fill sizes="(max-width: 600px) 100vw, (max-width: 1023px) 50vw, 33vw" /><span className="service-icon"><Icon size={22} /></span></div><div className="service-copy"><span className="micro-label">{s.tag}</span><h3>{s.title}</h3><p>{s.description}</p><a href={createWhatsAppUrl(enquiry(s.title.toLowerCase()))} target="_blank" rel="noopener noreferrer">Enquire on WhatsApp <ArrowUpRight size={17} /></a></div></motion.article></Reveal>; })}</div></div></section>;
}
function BenefitsSection() {
  const benefits = [[MessageCircle, 'Direct booking', 'Talk directly with the team, with no complicated booking flow.'], [Phone, 'A message is all it takes', 'Share your travel details in seconds on WhatsApp.'], [Route, 'More ways to travel', 'Local, airport, outstation, family and corporate journeys.'], [CarFront, 'A vehicle that fits', 'Discuss your passenger count, luggage and vehicle preference.'], [ShieldCheck, 'A real conversation', 'Prefer to talk? Call the team and discuss your requirements.'], [CalendarDays, 'Plans made around you', 'Share your pickup, destination and date for trip-specific assistance.']] as const;
  return <section className="section" id="why-us"><div className="container benefits-layout"><Reveal className="benefits-intro"><Heading eyebrow="THE GANPATI DIFFERENCE" title="More convenience.
Less travel stress." text="Because booking the ride should be the easy part of your journey." /><a href="#booking" className="text-link">Let’s plan your ride <ArrowRight size={18} /></a><div className="benefit-decor"><Route size={58} strokeWidth={1} /><span>From your first message<br />to your next destination.</span></div></Reveal><div className="benefits-grid">{benefits.map(([Icon, title, copy], i) => <Reveal key={title} delay={(i % 2) * 0.08}><Icon size={24} /><h3>{title}</h3><p>{copy}</p></Reveal>)}</div></div></section>;
}
function FleetSection() {
  return <section className="section fleet-section" id="fleet"><div className="container"><Reveal><Heading eyebrow="THE RIGHT FIT FOR YOUR TRIP" title="Your people. Your plans. Your car." text="Choose the right car for your journey, from everyday city rides to out-of-town adventures." centered /></Reveal><div className="fleet-grid">{fleet.map((f, i) => <Reveal key={f.name} delay={i * 0.08}><motion.article className="fleet-card" whileHover={{ y: -5 }}><div className="fleet-image"><span className="fleet-number">0{i + 1}</span><Image src={`/images/${f.image}.webp`} alt={`${f.name} vehicle illustration, actual vehicle subject to availability`} fill sizes="(max-width: 767px) 100vw, 33vw" /></div><div className="fleet-copy"><h3>{f.name}</h3><p>{f.caption}</p><div className="fleet-tags">{f.tags.map(t => <span key={t}><Check size={12} />{t}</span>)}</div><a href={createWhatsAppUrl(enquiry(f.name === 'Group Travel' ? 'a vehicle for group travel' : `a ${f.name}`))} target="_blank" rel="noopener noreferrer" className="fleet-cta">{f.cta}<ArrowUpRight size={18} /></a></div></motion.article></Reveal>)}</div><p className="fleet-note"><CarFront size={17} /> Need an Innova / Crysta or a 7-seater? <a href={createWhatsAppUrl(enquiry('an Innova / Crysta or 7-seater'))} target="_blank" rel="noopener noreferrer">Just ask us.</a> All vehicles subject to availability.</p></div></section>;
}
function TourismSection() {
  const [selected, setSelected] = useState(destinations[0]);
  return <section className="section tourism-section"><div className="container"><Reveal className="tourism-layout"><div className="tourism-copy"><Heading eyebrow="TAKE THE SCENIC ROUTE" title="A little escape.
A lot to discover." text="Explore Ranchi & Jharkhand your way. Plan a family outing, chase a waterfall or head for the hills." /><div className="destination-chips" aria-label="Choose a sightseeing destination">{destinations.map(d => <button type="button" key={d} aria-pressed={selected === d} className={selected === d ? 'selected' : ''} onClick={() => setSelected(d)}>{d}{selected === d && <Check size={13} />}</button>)}</div><div className="destination-summary" aria-live="polite"><MapPin size={18} /><span>Your next stop: <strong>{selected}</strong></span></div><WhatsApp message={`Hello ${business.name}, I am planning a trip to ${selected}. Please share available taxi options and fare details.`}>Plan This Trip</WhatsApp></div><div className="tourism-image"><Image src="/images/waterfall-tour.webp" alt="Illustrative waterfall in a lush landscape inspired by Jharkhand" fill sizes="(max-width: 767px) 100vw, 50vw" /><div className="tourism-image-label"><span>GO BEYOND THE EVERYDAY</span><strong>Closer to nature.<br />Further from routine.</strong><span>Illustrative Jharkhand-inspired scenery</span></div><span className="explore-stamp">LET’S GO<br /><ArrowUpRight size={25} />EXPLORE</span></div></Reveal></div></section>;
}
function ReviewsSection() {
  return <section className="section pale-section reviews-section" id="reviews"><div className="container"><Reveal><Heading eyebrow="JOURNEYS. EXPERIENCES. STORIES." title="What our customers say" text="Real journeys deserve real stories. Verified customer reviews will appear here when available." centered /></Reveal><div className="reviews-grid">{testimonials.length ? testimonials.map(t => <Reveal key={t.name} className="review-card"><Quote size={25} />{t.rating !== undefined && <span aria-label={`${t.rating} out of 5 stars`}>{'★'.repeat(t.rating)}</span>}<blockquote>{t.text}</blockquote><strong>{t.name}</strong><a href={t.sourceUrl} rel="noopener noreferrer" target="_blank">Read original review <ArrowUpRight size={14} /></a></Reveal>) : testimonialPlaceholders.map(t => <Reveal key={t.label} className="review-card placeholder-review"><Quote size={25} /><span className="placeholder-label">REVIEW PLACEHOLDER</span><h3>{t.label}</h3><p>{t.note}</p><span className="review-placeholder-note">Awaiting verified testimonial</span></Reveal>)}</div></div></section>;
}
function HowItWorks() {
  return <section className="section"><div className="container"><Reveal><Heading eyebrow="FROM A MESSAGE TO YOUR NEXT MILE" title="Your ride, in 3 simple steps." text="No apps to download. No complicated forms. Just a conversation." centered /></Reveal><div className="steps-grid">{[[MessageCircle, 'Share your journey', 'Tell us your pickup, destination, travel date and vehicle preference.'], [Wallet, 'Check availability & fare', 'Connect through WhatsApp or a call and discuss the options for your trip.'], [BadgeCheck, 'Confirm your ride', 'Agree on the travel details with the team and confirm your booking.']].map(([Icon, title, copy], i) => { const I = Icon as LucideIcon; return <Reveal key={String(title)} delay={i * 0.13} className="step"><span className="step-number">0{i + 1}</span><div className="step-icon"><I size={29} /></div><h3>{String(title)}</h3><p>{String(copy)}</p></Reveal>; })}</div><div className="center-cta"><WhatsApp>Start Booking on WhatsApp</WhatsApp></div></div></section>;
}
function ObjectionsSection() {
  const questions = [['Wondering about the fare?', 'Your route, vehicle and travel plans shape the fare. Send your details to get an enquiry started.'], ['Short on time?', 'A WhatsApp message or a quick call is all you need to begin.'], ['Have a vehicle in mind?', 'Tell us your preference. We’ll discuss what’s available for your travel date.'], ['Heading out of town?', 'Enquire for local and outstation journeys with your route and dates.'], ['Catching a flight?', 'Share your flight timing and ask about Ranchi Airport pickup or drop.'], ['Travelling together?', 'Share your passenger count and luggage needs for a suitable option.']];
  return <section className="section questions-section"><div className="container"><Reveal><Heading eyebrow="A LITTLE CLARITY BEFORE YOU GO" title="Have questions before booking?" centered /></Reveal><div className="questions-grid">{questions.map(([title, text]) => <Reveal key={title}><Check size={18} /><div><h3>{title}</h3><p>{text}</p></div></Reveal>)}</div></div></section>;
}
function FAQSection() {
  const [active, setActive] = useState<number | null>(0);
  return <section className="section" id="faq"><div className="container faq-layout"><Reveal className="faq-intro"><Heading eyebrow="GOOD TO KNOW" title="A few answers
before you set off." text="Everything you need to know about booking your taxi." /><div className="faq-help"><span className="round-icon"><Phone size={22} /></span><h3>Prefer a quick conversation?</h3><p>We’re just a call away.</p><a href={`tel:${business.phone}`}>{business.phoneDisplay}<ArrowUpRight size={17} /></a></div></Reveal><Reveal className="faq-list">{faqs.map(([q, a], i) => <div className={`faq-item ${active === i ? 'is-open' : ''}`} key={q}><h3><button type="button" id={`question-${i}`} onClick={() => setActive(active === i ? null : i)} aria-expanded={active === i} aria-controls={`answer-${i}`}><span>{q}</span><ChevronDown size={18} /></button></h3><AnimatePresence initial={false}>{active === i && <motion.div id={`answer-${i}`} role="region" aria-labelledby={`question-${i}`} className="faq-answer" initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.25 }}><p>{a}</p></motion.div>}</AnimatePresence></div>)}</Reveal></div></section>;
}
function FinalCTA() {
  return <section className="final-section"><div className="container"><Reveal className="final-cta"><div className="final-copy"><span className="eyebrow light"><span />THE NEXT MILE IS YOURS</span><h2>Ready for your<br />next ride?</h2><p>Share your pickup location, destination and travel date.<br />Let’s get your journey started.</p><div className="cta-row"><WhatsApp /><Call className="light-outline" /></div><a className="final-phone" href={`tel:${business.phone}`}><Phone size={17} />{business.phoneDisplay}</a><span className="final-services">Local · Airport · Outstation · Sightseeing · Family Travel</span></div><div className="final-image"><Image src="/images/hero-taxi.webp" alt="Illustrative travel taxi ready for a scenic journey" fill sizes="(max-width: 767px) 100vw, 50vw" /><div /></div></Reveal></div></section>;
}
function Footer() { return <footer className="footer"><div className="container"><div className="footer-grid"><div className="footer-brand"><a href="#home"><Image src="/images/logo.png" alt={business.name} width={136} height={102} /></a><p>Your city. Your destination.<br />Your travel partner in Ranchi.</p><span className="gst">GST: {business.gst}</span></div><div><h3>Find us in Ranchi</h3><address>{business.address}</address><span className="footer-local"><MapPin size={14} />Lalpur, Ranchi, Jharkhand</span></div><div><h3>Let’s plan your journey</h3><a href={`tel:${business.phone}`}>{business.phoneDisplay}</a><a href={`tel:${business.secondaryPhone}`}>{business.secondaryPhoneDisplay}</a><a className="email" href={`mailto:${business.email}`}>{business.email}</a><a className="email" href={`mailto:${business.secondaryEmail}`}>{business.secondaryEmail}</a></div><div className="footer-nav"><h3>Explore</h3>{nav.slice(1).map(([name, href]) => <a href={href} key={href}>{name}</a>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {business.name}. All rights reserved.</span><span>Images are illustrative. Vehicle availability is confirmed on enquiry.</span><a href="#home" aria-label="Back to top"><ArrowDown size={16} /></a></div></div></footer>; }
export default function LandingPage() { return <MotionConfig reducedMotion="user"><a href="#main" className="skip-link">Skip to content</a><Header /><main id="main"><Hero /><QuickBooking /><ProblemSection /><CostSection /><SolutionSection /><ServicesSection /><BenefitsSection /><FleetSection /><TourismSection /><ReviewsSection /><HowItWorks /><ObjectionsSection /><FAQSection /><FinalCTA /></main><Footer /><a className="floating-whatsapp" href={createWhatsAppUrl(enquiry())} target="_blank" rel="noopener noreferrer" aria-label="Chat on WhatsApp"><span>Chat on WhatsApp</span><MessageCircle size={27} /></a><div className="mobile-cta"><Call /><WhatsApp>WhatsApp</WhatsApp></div></MotionConfig>; }
